### ISSUE TITLE
self.signing_key.encode() in client.py encodes the seed

### ISSUE THREAD

**Issue by EphTron** [xxblx/tornado-app-template#2]
Hi, I am currently playing around with your tornado app template and try to write a c# client for it. 
I am not a crypto expert which is probably the reason why I stumbled over a line in your client.py file when I tried to figure out how things work.
In line 76 `signing_key_bytes = self.signing_key.encode()` is called which actually encodes the signing_key._seed.
`if signing_key_bytes == self.signing_key._seed:`   --> results in _true_ for me
By the name of the variable I assume that this is not intended, but as this is not really my field I thought I'd ask.
What is this line supposed to do? 
Thanks in advance

**Comment by xxblx** [comment]
Hey @EphTron, 

Sorry for the delayed response.

I haven't used this code for a while, but as far as I remember this line was aimed to create a bytes object and didn't apply any changes to the key itself.

i.e. 
> if signing_key_bytes == self.signing_key._seed: --> results in true for me

Yes, `self.signing_key.encode() == self.signing_key._seed == bytes(self.signing_key)`. And, unfortunately, I don't remember why I treated `self.signing_key` exactly with encode method like if it was a string-like. 

> I am currently playing around with your tornado app template and try to write a c# client for it.

Please, keep in mind, the code in the repository is outdated. It would make sense at least to update the code with newer syntax supported by python and tornado and audit the crypto side.
